# Generated by Django 4.1.3 on 2023-01-29 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_docente_vinculacion', models.IntegerField()),
                ('rol_docente_tutor', models.IntegerField()),
                ('rol_estudiante', models.IntegerField()),
                ('rol_coordinador_general', models.IntegerField()),
                ('rol_voordinador_carrera', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('cedula', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=10)),
                ('direccion', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('tipo_solicitud', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=20)),
                ('clave', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersonaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.CharField(max_length=15)),
                ('carrera', models.CharField(max_length=25)),
                ('jornada', models.CharField(max_length=10)),
                ('catalogo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.catalogo')),
                ('idPersona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=60)),
                ('opciones', models.CharField(max_length=10)),
                ('observaciones', models.CharField(max_length=10)),
                ('aprobar', models.BooleanField(default=False)),
                ('dirigido', models.BooleanField(default=False)),
                ('estado', models.BooleanField(default=False)),
                ('idTipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipopersonacatalogo')),
            ],
        ),
        migrations.CreateModel(
            name='Fundacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=70)),
                ('encargado', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('estado', models.BooleanField(default=False)),
                ('idTipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipopersonacatalogo')),
            ],
        ),
    ]
